"""empty message

Revision ID: 7d87bcc9fee2
Revises: 
Create Date: 2019-11-25 20:30:46.107385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d87bcc9fee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.Column('passWord', sa.String(length=10), nullable=True),
    sa.Column('balance', sa.FLOAT(precision=10, asdecimal=4), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
